config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions do
    resources :answer
  end
    
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :answer, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  is_impressionable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_one :answer

  validates :language, presence: true
  validates :framework, presence: true
  validates :hobby, presence: true
  validates :desired_engineer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  validates :nickname, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: "Include both letters and numbers" }
  has_many :questions
  has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #impressionist actions: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?
  #before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: :index
  require 'ruby/openai'
  require 'rainbow'

  def index
    @user_count = User.count
    @question_count = Question.count
    if user_signed_in? && current_user.questions.exists?
      @question = current_user.questions.last
      @answer = @question.answer
    end

  end
  
  def new
    @question = Question.new
  end

  def create
    require 'ruby/openai'
    @question = Question.new(question_params)
    client = OpenAI::Client.new(access_token:ENV["OPENAI_API_KEY"])

      response = client.chat(
      parameters: {
          model: "gpt-3.5-turbo",
          # messages: [{ role: "user", content: "hello!" }],
          # max_tokens: 10
          messages: [{ role: "user", content: "あなたは優秀なキャリアアドバイザーです。私はエンジニアになりたいです。得意なプログラミング言語は#{params[:question][:language]}、フレームワークは#{params[:question][:framework]}です。趣味は#{params[:question][:hobby]}、前職は#{params[:question][:former_job]}です。#{params[:question][:desired_engineer]}になりたいです。作ればいいポートフォリオの案を１個ください。回答は日本語で300文字以内にしてください。" }],
          max_tokens: 500
      })
    
    @answer = Answer.new(answer: response.dig("choices", 0, "message", "content"), question: @question, user_id: current_user.id)
    if @answer.save
      @question.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:language,:framework, :hobby, :former_job, :desired_engineer).merge(user_id: current_user.id)
  end

  def answer_params
    params.permit(:answer).merge(question_id: @question.id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortHelper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'bootstrap' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>%>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<%= render "shared/header" %>
  <% if user_signed_in? && current_user.questions.exists? %>
  <div class="row align-items-md-stretch justify-content-center">
    <div class="col-md-8">
      <div class="h-100 p-5 text-white bg-dark rounded-3">
        <h2>Port-Helperからの解答</h2>
        <div id="typed-strings">
        <p><%= @answer.answer %></p>
        </div>
        <span id="typed"></span>
        <h2>プロフィール</h2>
        プログラミング言語 : <%= @question.language %><br>
        フレームワーク : <%= @question.framework %><br>
        趣味 : <%= @question.hobby %><br>
        経験したお仕事 : <%= @question.former_job %><br>
        希望するエンジニア : <%= @question.desired_engineer %><br>
      </div>
    </div>
    <div class="col-md-3">
      <div class="h-100 p-5 bg-light border rounded-3">
        <h2>質問はココ</h2>
        <%= link_to "プロフィール入力", new_question_path, class: 'btn btn-outline-secondary', type: 'button' %>
      </div>
    </div>
  </div>
  <% else %>
  <div class="row align-items-md-stretch justify-content-center">
    <div class="col-md-8">
      <div class="h-100 p-5 text-white bg-dark rounded-3">
        <h2>Port-Helperの使い方</h2>
        <div id="typed-strings">
        <p>Port-Helperは、未経験エンジニアによって作られました。作られた目的はあなたのエンジニアとしてのキャリアを支援し、あなたの持つスキルや興味を最大限に引き出し、最適なポートフォリオを作成するためのアドバイスを伝えるためです。
          エンジニアとしての成長は、自分自身が積極的に取り組むことが不可欠です。しかし、Port-Helperが提供するサービスを使うことで、方向性を定め効率的かつ効果的にスキルアップすることができるヒントを得ることができます。私は、あなたのエンジニアとしてのキャリアを支援したいと考えています。
          さあ、あなたも今すぐPort-Helperを使って、自分のスキルアップの可能性を広げましょう！Let's Port-Helper!!!</p>
        </div>
        <span id="typed"></span>

      </div>
    </div>
    <div class="col-md-3">
      <div class="h-100 p-5 bg-light border rounded-3">
        <br>
        <h2>ユーザー数: <%= @user_count %></h2>
        <br>
        <h2>解答数: <%= @question_count %></h2>
        <br>
        <%= link_to "プロフィール入力", new_question_path, class: 'btn btn-outline-secondary', type: 'button' %>
      </div>
    </div>
  </div>
  <div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="mt-5" style="margin-top: 60px !important;">Github Contributions</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="github-link">
        <i class="fab fa-github-square"></i>
        <p>芝生は生やしてなんぼ！</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <a href="https://github.com/taichi0221" target="_blank">
        <img src="https://grass-graph.appspot.com/images/taichi0221.png?" class="img-fluid">
      </a>
    </div>
  </div>
  <% end %>
<%= render "shared/footer" %>

app/views/questions/new.html.erb
<%= render "shared/header" %>
  <div class="row align-items-md-stretch justify-content-center">
    <div class="col-md-8">
      <div class="h-100 p-5 text-white bg-dark rounded-3">
        <%= form_with model: @question, url: questions_path ,local: true do |f| %>
        <div id ="after_submit" >
          <h2>プロフィール入力</h2>
          <%= f.label :language, 'プログラミング言語' %>
          <%= f.text_field :language, id: "language_input",class: "form-control", placeholder: "得意なプログラミング言語を入力してください" %>
          <%= f.label :framework, 'フレームワーク'%>
          <%= f.text_field :framework, id: "framework_input",class: "form-control", placeholder: "得意なフレームワークを入力してください" %>
          <%= f.label :hobby, '趣味' %>
          <%= f.text_field :hobby, id: "hobby_input", class: "form-control", placeholder: "趣味を入力してください" %> 
          <%= f.label :former_job ,'経験したお仕事（任意）'%>
          <%= f.text_field :former_job, class: "form-control", placeholder: "前職を入力してください" %> 
          <div class="form-group">
            <%= f.label :desired_engineer, '目指すエンジニア' %>
            <%= f.select :desired_engineer, options_for_select([
              ['ソフトウェアエンジニア', 'ソフトウェアエンジニア'],
              ['データエンジニア', 'データエンジニア'],
              ['ネットワークエンジニア', 'ネットワークエンジニア'],
              ['セキュリティエンジニア', 'セキュリティエンジニア'],
              ['フロントエンドエンジニア', 'フロントエンドエンジニア'],
              ['バックエンドエンジニア', 'バックエンドエンジニア'],
              ['AIエンジニア', 'AIエンジニア'],
              ['モバイルエンジニア', 'モバイルエンジニア'],
              ['IoTエンジニア', 'IoTエンジニア'],
              ['WEBデザイナー', 'WEBデザイナー']
              ]), { include_blank: '目指すエンジニアを選択してください' }, class: 'form-control', id: "desired_engineer_input" %><br>
            <%= f.submit "聞く！", class: "btn btn-primary", id: "submit", style: "display:none;"%>
          </div>
        </div>
        <% end %>
        <div id = "before_submit" >
          <div class="ratio ratio-16x9">
            <iframe src="https://www.youtube.com/embed/fMEYb0W3_ec?rel=0" title="YouTubeビデオ" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>      
    <div class="col-md-3">
      <div class="h-100 p-5 bg-light border rounded-3">
        <div id = "before_submit2">
        <h1>作成中</h1>
          <div id="typed-strings2">
            <p>大急ぎで作っています
            <br>おまちください
            <br>←作成中の風景です
            </p> 
          </div>
          <span id="typed2"></span>
        </div>  
      </div>
    </div>
  </div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-3 bg-light">
  <div class="container text-center">
    <div class="row">
        <p class="mb-0">Copyright &copy; 2023 Taichi Muta
      
    </div>
  </div>
</footer>
<footer class="py-3 bg-light">
  <div class="container text-center">
    <a href="#top" class="text-dark me-4">Back to top</a>
    <a href="/contact" class="text-dark">Contact</a>
  </div>
</footer>
<%#<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>%>

app/views/shared/_header.html.erb
<div class="container">
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
    </a>

    <div class="col-md-4 text-end">
    <% if user_signed_in? %>
      <%= link_to current_user.nickname, root_path , class: "btn btn-outline-primary me-2" %>
      <%= link_to "ログアウト", destroy_user_session_path,method: :delete, class: "btn btn-outline-primary" %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-primary me-2" %>
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-primary" %>
    <% end %>
    </div>
  </header>
</div>